document.addEventListener('DOMContentLoaded', () => {
  const sitemapUrl = document.getElementById('sitemap-url');
  const userAgent = document.getElementById('user-agent');
  const disallow = document.getElementById('disallow');
  const allow = document.getElementById('allow');
  const output = document.getElementById('output');
  const btnGenerate = document.getElementById('btn-generate');
  const btnCopy = document.getElementById('btn-copy');
  const btnDownload = document.getElementById('btn-download');

  btnGenerate.addEventListener('click', () => {
    const ua = userAgent.value.trim() || '*';
    const disallowPaths = disallow.value.split('\n').map(l => l.trim()).filter(l => l);
    const allowPaths = allow.value.split('\n').map(l => l.trim()).filter(l => l);
    const sitemap = sitemapUrl.value.trim();

    let txt = `# robots.txt generated by ToolWools\n`;
    txt += `User-agent: ${ua}\n`;
    if (allowPaths.length > 0) allowPaths.forEach(p => { txt += `Allow: ${p}\n`; });
    if (disallowPaths.length > 0) disallowPaths.forEach(p => { txt += `Disallow: ${p}\n`; });
    else txt += `Disallow:\n`;
    if (sitemap) txt += `\nSitemap: ${sitemap}\n`;

    output.value = txt;
    showToast('robots.txt generated!', 'success');
  });

  btnCopy.addEventListener('click', () => {
    if (!output.value) return;
    navigator.clipboard.writeText(output.value).then(() => showToast('Copied!', 'success'));
  });

  btnDownload.addEventListener('click', () => {
    if (!output.value) return;
    const blob = new Blob([output.value], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'robots.txt';
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 3000);
    showToast('robots.txt downloaded!', 'success');
  });
});
